version: '3.4'

services:
  taskmanagement.api:
    image: ${DOCKER_REGISTRY-}taskmanagementapi
    build:
      context: .
      dockerfile: TaskManagement.Api/Dockerfile

  taskmanagement.web.ui:
    image: ${DOCKER_REGISTRY-}taskmanagementwebui
    build:
      context: task-management-web-ui
      dockerfile: Dockerfile
    container_name: taskmanagement.web.ui
