version: '3.4'

services:
  users.db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: tasks.db
    environment:
      - SA_PASSWORD=DevEnvPassword123
      - ACCEPT_EULA=Y
    ports:
      - "1430:1433"

  taskmanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=tasks.db;Database=tasksDb;User Id=sa;Password=DevEnvPassword123;Encrypt=False;
      - ServiceAddresses__FrontendUrl=http://localhost:3000
    ports:
      - "5000:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  taskmanagement.web.ui:
    build:
      context: task-management-web-ui
      dockerfile: Dockerfile 
      args:
        # URL for the API
        REACT_APP_TASKS_API_BASE_URL: http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - taskmanagement.api