// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.Api.DataAccess;

#nullable disable

namespace TaskManagement.Api.Migrations
{
    [DbContext(typeof(TasksDbContext))]
    [Migration("20241111165506_initialize-db")]
    partial class initializedb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.Api.DataAccess.Models.TaskModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("52fedbfa-b0e2-4ff8-985c-92099e04cac0"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7727),
                            Description = "Description of Task 1",
                            Name = "Task 1",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("be98e1d3-1759-4dad-bfa7-c66d0725959f"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7731),
                            Description = "Description of Task 2",
                            Name = "Task 2",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("81cdddb5-1880-4f84-8e55-da4ef0a3bc5b"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7733),
                            Description = "Description of Task 3",
                            Name = "Task 3",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("680604d3-2d72-4664-96df-883e9eae4585"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7735),
                            Description = "Description of Task 4",
                            Name = "Task 4",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("10f85dde-111f-4247-b1ac-929f4ab48a8c"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7737),
                            Description = "Description of Task 5",
                            Name = "Task 5",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("fff94f9d-1be6-402c-80d4-ebc76957dec5"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7738),
                            Description = "Description of Task 6",
                            Name = "Task 6",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("2d70788b-3e88-47ca-a86f-a0ec9f24cf4e"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7740),
                            Description = "Description of Task 7",
                            Name = "Task 7",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("6aa5250a-b64e-4467-864f-0f80b46b7844"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7741),
                            Description = "Description of Task 8",
                            Name = "Task 8",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("aaa0613e-eb6a-43aa-ab41-93b892ac1f3a"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7742),
                            Description = "Description of Task 9",
                            Name = "Task 9",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("03a28cbe-966a-4209-a7cb-fd5269bf2820"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7744),
                            Description = "Description of Task 10",
                            Name = "Task 10",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("93ac9645-2566-42b0-ab6c-788509c81cbe"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7745),
                            Description = "Description of Task 11",
                            Name = "Task 11",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("ba66531f-eca3-436f-94b9-8416fabadd58"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7747),
                            Description = "Description of Task 12",
                            Name = "Task 12",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("6c1cbfe3-5acd-40ad-96e6-acf27fca8c24"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7748),
                            Description = "Description of Task 13",
                            Name = "Task 13",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b9333151-42d3-4f3f-8b0b-cabe6ae1d37f"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7750),
                            Description = "Description of Task 14",
                            Name = "Task 14",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("e35016e7-670a-4cf5-831a-38d37aceb65a"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7751),
                            Description = "Description of Task 15",
                            Name = "Task 15",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("5372af38-357a-4407-a148-313aa7109a4d"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7753),
                            Description = "Description of Task 16",
                            Name = "Task 16",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("c8aa03fc-fd7b-4665-9aab-68672d63a528"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7754),
                            Description = "Description of Task 17",
                            Name = "Task 17",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("2cee431a-3491-4125-b0a5-ef01f1d98e9c"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7756),
                            Description = "Description of Task 18",
                            Name = "Task 18",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("3e897919-05ee-4885-a1e0-2c8cfa489c2d"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7757),
                            Description = "Description of Task 19",
                            Name = "Task 19",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ac767dc0-0c32-4b65-a2de-a5fd1ac77262"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7758),
                            Description = "Description of Task 20",
                            Name = "Task 20",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("f36d6407-9940-4ab2-b7cf-17ce52cc73d6"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7760),
                            Description = "Description of Task 21",
                            Name = "Task 21",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("e44df732-b8bd-4150-a3a0-6a6d8f958c03"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7761),
                            Description = "Description of Task 22",
                            Name = "Task 22",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3bfbb605-435c-44b1-ba2e-469911f93a62"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7763),
                            Description = "Description of Task 23",
                            Name = "Task 23",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("8c739263-6e73-4846-a22a-3ba74eea28f2"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7764),
                            Description = "Description of Task 24",
                            Name = "Task 24",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("c8f8bba7-b018-46df-8ea9-c72733c7c401"),
                            CreatedAt = new DateTime(2024, 11, 11, 16, 55, 6, 468, DateTimeKind.Utc).AddTicks(7765),
                            Description = "Description of Task 25",
                            Name = "Task 25",
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
